### ISSUE TITLE
plans to make js turbo-compatible

### ISSUE THREAD

**Issue by masterkain** [adminkit/adminkit#130]
hello,
thanks for providing this product, I'm almost positive it will be used in our next open source product, however it doesn't seems to be hotwire-turbo compatible, are there any plans in this regard? thanks

**Comment by paullaros** [comment]
Glad to hear you're considering using our product. I'm afraid I have to close this issue because it doesn't follow the [bug report template](https://github.com/adminkit/adminkit/issues/new?assignees=&labels=bug&template=bug_report.md). I have no idea what kind of issues you're running into or how to re-create those issues.
