### ISSUE TITLE
css, charts and maps does not work when integrated with the react in dev mode

### ISSUE THREAD

**Issue by 21pranav** [adminkit/adminkit#132]
css, charts, and maps do not work when integrated with the react in dev mode
[
![Untitled](https://user-images.githubusercontent.com/20351961/220313929-6cf00f95-4a11-4028-ac51-c30df4e50491.png)
](url)

**Comment by paullaros** [comment]
Hey @21pranav, that's because the JavaScript included is not made for React-based applications. If you wish to use Bootstrap in combination with React, we recommend the [React Bootstrap](https://react-bootstrap.github.io/) library.

Closing this as this has nothing to do with the AdminKit package. We might launch a React-based version in the future.
