### ISSUE TITLE
Document Webpack configuration

### ISSUE THREAD

**Issue by tacman** [adminkit/adminkit#90]
I'm much more of a server-side developer, so I might be confused about how themes like this are supposed to be installed.  Specifically, I use Symfony and webpack encore, which simplifies configuring the front-end assets (https://symfony.com/doc/current/frontend.html)

What I _think_ I want is a process like this:

* yarn add bootstrap@next, @popperjs/core, adminkit/adminkit, etc.
*  in app.js, add require('~adminkit'); (and bootstrap?  Or is that included? )
* in app.scss, add @import("~adminkit");  app.js required app.scss, and the sass compiler then combines everything.

Absent a flow like this, I find myself copying more files than I think I should.  I'm trying to avoid directly copying files into my project and committing them, but rather installing them so the latest upgrades are installed when I run yarn upgrade.  And I don't want my project to store the minified files, when I deploy on heroku webpack and sass are run to create the appropriate file.

Obviously, I'm talking about the js and css files only -- the HTML files need to be refactors as twig or view for the specific application, and those are checked in.

AdminLTE has a cool companion bundle (AdminLTEBundle) that put some of the widgets into macros that could easily generate the twig.  I've thought about doing something like that with the bundle I'm working on, but something about the way I'm installing the assets seems wrong.

**Comment by paullaros** [comment]
Hi @tacman,

The vast majority of the codebase is ensuring that the various external modules work well together. Compared to other npm modules, who usually do one thing well, AdminKit does a lot of things on multiple fronts (configuration files, scss, JavaScript, images and HTML), and a large part of our users end up modifying the source files directly. Because of this we're not entirely sure it makes sense to publish the package to npm.

For now, you could use your own published package (#89) and we'll take this request in consideration. Closing this for now.
